Improve Lunacolors.md
Rosettea/Hilbish pull request #331
Opened 2024-12-16 00:30 UTC by Naadiyaar

---
- [x] I have reviewed CONTRIBUTING.md.
- [x] My commits and title use the [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) format.
- [x] I have documented changes and additions in the CHANGELOG.md.
---
Improved document formatting and mentioned 2 Lunacolors styles; reset and bright backgrounds.

2024-12-18 15:46 UTC, TorchedSammy commented on docs/lunacolors.md
>  Styles:
```suggestion
Styles:  
```

2024-12-18 15:46 UTC, TorchedSammy commented on docs/lunacolors.md
> +For example, bright blue would be written as `brightBlue`, a cyan background as
```suggestion
For example, bright blue would be written as `brightBlue`, a cyan background as
```

2024-12-18 15:46 UTC, TorchedSammy commented on docs/lunacolors.md
> +These can also be combined. Note that appropriate camel casing must be applied.
```suggestion
These can also be combined. Note that appropriate camel casing must be applied.
```

2024-12-18 15:47 UTC, TorchedSammy requested changes
small markdown changes. make sure to *actually* read the contributing.md and make your commits conventional and PR title.

2024-12-29 08:22 UTC, Naadiyaar commented
Oh! I just realized it's possible to append suggested changes without a new commit.
Also about bad commit titles, apparently it's not possible to modify their message without making a new branch.

if you think all these will mess up the project's commit tree close this pr and I will make a new one.

2024-12-29 15:24 UTC, TorchedSammy commented
>Also about bad commit titles, apparently it's not possible to modify their message without making a new branch.

amend them and force push

2024-12-29 19:48 UTC, Naadiyaar commented
omg this is annoying. I forgot to update my patch-1 branch with the latest changes in the codebase.
I'll try again :(
sorry

2025-05-05 00:40 UTC, sammy-ette approved these changes

2025-05-05 00:41 UTC, merged